#!/bin/bash

# Purpose: 
# Created Date:  Thursday 19 May 2022 04:35:50 PM IST
# Author: Harsh Panchal

# Note 

# START #

banner (){
    clear

    printf "\e[0m\n"
    printf "\e[1;33m   _______             _     \e[0m\e[1;32m  _____       \e[0m\n"
    printf "\e[1;33m  |__   __|           | |    \e[0m\e[1;32m |_   _|      \e[0m\n"
    printf "\e[1;33m     | |_ __ __ _  ___| | __ \e[0m\e[1;32m   | |  _ __  \e[0m\n"
    printf "\e[1;33m     | |  __/ _  |/ __| |/ / \e[0m\e[1;32m   | | |  _ \ \e[0m\n"
    printf "\e[1;33m     | | | | (_| | (__|   <  \e[0m\e[1;32m  _| |_| |_) |\e[0m\n"
    printf "\e[1;33m     |_|_|  \__,_|\___|_|\_\ \e[0m\e[1;32m |_____| .__/ \e[0m\n"
    printf "\e[1;32m                                    | |    \e[0m\n"
    printf "\e[1;32m                                    |_|    \e[0m\n"
    printf "\e[0m\n"
# printf "\e[0m\e[1;33m    Created By HTR-TECH \e[0m\e[1;31m(\e[0m\e[1;33m TAHMID RAYAT \e[0m\e[1;31m)\e[0m\n"
# https://github.com/htr-tech/track-ip
}

menu (){

    printf "\e[0m\n"
    printf "\e[0m\e[1;31m  [\e[0m\e[1;37m01\e[0m\e[1;31m]\e[0m\e[1;33m My IP\e[0m\n"
    printf "\e[0m\e[1;31m  [\e[0m\e[1;37m02\e[0m\e[1;31m]\e[0m\e[1;33m Track Ip\e[0m\n"
    printf "\e[0m\e[1;31m  [\e[0m\e[1;37m00\e[0m\e[1;31m]\e[0m\e[1;33m Exit\e[0m\n"
    printf "\e[0m\n"
    read -p $'  \e[1;31m[\e[0m\e[1;37m~\e[0m\e[1;31m]\e[0m\e[1;92m Select An Option \e[0m\e[1;96m: \e[0m\e[1;93m\en' option

    if [[ $option == 1 || $option == 01 ]] 
    then
        myipaddr

    elif [[ $option == 2 || $option == 02 ]]
    then
        useripaddr

    elif [[ $option == 0 || $option == 00 ]]
    then
        sleep 1
        echo "\e[0m\n"
        echo "\e[0m\n"
        exit 1

    else
        printf " \e[1;91m[\e[0m\e[1;97m!\e[0m\e[1;91m]\e[0m\e[1;93m Invalid option \e[1;91m[\e[0m\e[1;97m!\e[0m\e[1;91m]\e[0m\n"
        sleep 1
    
        banner
        menu
    fi

}
